---
- name: Install common packages
  hosts: all
  become: true

  vars:
    packages_fedora:
      - git
      - gh
      - curl
      - fzf
      - fd-find
      - zoxide
      - ripgrep
      - tree
      - tmux
      - bat
      - cmake
      - make
      - gcc
      - gcc-c++
      - autoconf
      - automake
      - golang
      - cargo
      - python3
      - ansible
      - podman
      - doctl
      - keepassxc
      - neovim

  tasks:
    - name: Install packages (Fedora)
      dnf:
        name: "{{ packages_fedora }}"
        state: present
      when: ansible_facts["os_family"] == "RedHat"

